name: pegasus_tool
description: PegasusTool

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.21.2+16369

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_review: ^2.1.2+1
  auto_size_text: ^3.0.0
  charts_flutter: ^0.12.0
  dio: ^5.3.1
  expandable: ^5.0.1
  fancy_bottom_navigation:
    git:
      url: https://github.com/Kingpin-Apps/fancy_bottom_navigation.git
  firebase_analytics: ^10.1.1
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  firebase_crashlytics: ^3.0.12
  firebase_database: ^10.0.10
  firebase_messaging: ^14.2.2
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^15.1.0+1
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.1.3
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.8.0
  launch_review: ^3.0.1
  logger: ^2.0.1
  number_display: ^3.0.0
  package_info: ^2.0.2
  path:
  percent_indicator: ^4.2.2
  pretty_dio_logger: ^1.1.1
  provider:
  qr_mobile_vision: ^4.0.1
  retrofit: ^4.0.1
  shared_preferences: ^2.0.17
  sk_onboarding_screen:
    git:
      url: https://github.com/Kingpin-Apps/SKOnboardingScreen.git
  sqflite:
  timeago: ^3.3.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.9
  uuid: ^3.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0

flutter_icons:
  image_path: "assets/web_hi_res_512.png"
  android: false
  ios: true

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_native_splash: ^2.0.0
  json_serializable: ^6.6.1
  retrofit_generator: ^7.0.8
  flutter_lints: ^2.0.1
  cider: ^0.1.3
  hive_generator: ^2.0.0
  mockito: ^5.3.2

flutter_native_splash:
  # run flutter pub pub run flutter_native_splash:create
  color: "#121212"
  fill: false
  android_disable_fullscreen: false
  fullscreen: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

scripts:
  build_runner: fvm flutter pub run build_runner build --delete-conflicting-outputs
  clean: fvm flutter clean
  pod_install: cd ios && pod install
  build: flutter pub run build_runner build --verbose --delete-conflicting-outputs
  build_ios_dev: flutter build ios --dart-define=POOL_TOOL_ENVIRONMENT=dev --release --no-codesign
  build_ios: flutter build ios --release --no-codesign
  build_android: flutter build apk --release
  bump_minor: cider bump minor
  bump_patch: cider bump patch
  bump_build: cider bump build
  fastlane_ios_beta: cd ios && fastlane beta
  changelog: cz changelog
  bump: cz bump